core/urls.py
from django.urls import path

from . import views

app_name = 'core'

urlpatterns = [
  path('', views.index, name='index'),
  path('contact', views.contact, name='contact'),
  path('products', views.products, name='products'),
]

sklep_kuba/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/', include('core.urls')),
]

core/models.py
from django.db import models
from datetime import date

class Contact(models.Model):
  telephone = models.CharField(max_length=12)
  email = models.CharField(max_length=100)
  address = models.CharField(max_length=200)

  def __str__(self):
    return self.address

class Product(models.Model):
  name = models.CharField(max_length=200)
  description = models.CharField(max_length=600, blank = True)
  image = models.ImageField(blank = True)
  pub_date = models.DateField(default=date.today)
  amount = models.IntegerField()

  def __str__(self):
    return self.name

class Price(models.Model):
  product = models.OneToOneField(Product, on_delete=models.DO_NOTHING, primary_key=True)
  amount = models.DecimalField(max_digits=6, decimal_places=2)
  currency = models.CharField(max_length=200)
  
  def __str__(self):
    return str(self.amount) + ' ' + self.currency

core/views.py
from django.shortcuts import render, get_object_or_404
from .models import Product, Contact

def index(request):
  return render(request, 'core/index.html')

def products(request):
  products = Product.objects.order_by('-pub_date')
  return render(request, 'core/products.html', {
    'list': products
  })

def contact(request):
  try:
    contact = Contact.objects.all()[:1].get()
    return render(request, 'core/contact.html', {
      'contact': contact
    })
  except ObjectDoesNotExist:
    return render(request, 'core/contact.html')
  

core/templates/core/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <link rel="stylesheet" type="text/css" href="{% static 'core/reset.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'core/layout.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'core/bootstrap.css' %}">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <title>{% block title %}Tytuł strony{% endblock %}</title>
    {% block styles %}{% endblock %}
  </head>
  <body>
    <header class="header">
      <div style="float:right">
        <span class="logo__brand">User</span>
        <i class="material-icons logo__icon">account_circle</i>
      </div>
        <navigation class="nav header__nav navigation">
          <ul class="list-inline">
            <li class="list-inline-item"><a href="{% url 'core:index' %}" style="color:green">Strona domowa</a></li>
            <li class="list-inline-item"><a href="{% url 'core:contact' %}" style="color:green">Strona kontaktowa</a></li>
            <li class="list-inline-item"><a href="{% url 'core:products' %}" style="color:green">Strona z produktami</a></li>
          </ul>
        </navigation>
    </header>
    <main class="content">
      {% block content %}{% endblock %}
    </main>
  </body>
</html>

core/templates/core/contact.html
{% extends "core/base.html" %}

{% block content %}
  {% if contact %}

    <table class="table">
      <tr>
        <th scope="col">Imię i nazwisko</th>
        <th>{{contact.telephone}}</th>
      </tr>
      <tr>
        <th scope="col">Email kontaktowy</th>
        <th>{{contact.email}}</th>
      </tr>
      <tr>
        <th scope="col">Adres kontaktowy</th>
        <th>{{contact.address}}</th>
      </tr>
      <tr>
        <th scope="col"></th>
        <th></th>
      </tr>

    </table>

  {% else %}
    <h5>Brak danych kontaktowych</h5>
  {% endif %}
{% endblock %}

core/templates/core/index.html
{% extends "core/base.html" %}


{% block content %}
  <article class="article">
    <header>
      <h1 class="article__title">Bajka o trzech świnkach<h1>
    </header>
    <div class="article__text">
      Dawno temu, w małej zaniedbanej chatce, mieszkały sobie z mamą trzy małe świnki. Były bardzo biedne, więc postanowiły, że wyruszą w świat w poszukiwaniu fortuny.

      I tak, pierwsza z nich zapakowała ulubione rzeczy, powiedziała mamie „do widzenia” i poszła.
      Nie uszła daleko, gdy zobaczyła ładną brukowaną drogę.
      - Jaka piękna droga – powiedziała pierwsza mała świnka. - chyba pójdę nią i przekonam się, co mnie na niej spotka.
      Niedługo potem ujrzała człowieka ze snopkiem słomy.
      - Dzień dobry panu – przywitała się grzecznie. - Niech mi pan sprzeda ten snopek słomy, przyda mi się na budowę domku.
      - Zgoda – odrzekł człowiek.
      ﻿


      I tak pierwsza mała świnka dała człowiekowi wszystkie pieniądze za snopek słomy. Potem zabrała się do pracy. Zaczęła wiązać słomę w pęczki i przymocowywać do kijów. Robiła to tak długo, aż wybudowała ścianę. Wreszcie, mała świnka samodzielnie zrobiła przytulny mały domek ze słomy i była bardzo zadowolona.
      Ale kiedy siedziała w środku i jadła pierwszą kolację w nowym domku, nadszedł zły wilk. Polował przez cały dzień w wielkim lesie, ale nie znalazł nic do jedzenia, więc był bardzo głodny. Nic dziwnego, że kiedy zobaczył malutki domek świnki, pomyślał: wreszcie znalazłem kolację! Zapukał do drzwi i zawołał:
      Mała świnko, uchyl drzwi
      Pozwól wejść do środka mi!
      Pierwsza świnka wyjrzała przez okno. Kiedy zobaczyła wielkiego złego wilka, zawołała:
      Nie otworzę drzwi przed tobą,
      Boś jest bardzo złą osobą!
      To bardzo rozwścieczyło wilka. Ryknął bardzo głośno:
      Jak się nadmę i jak dmuchnę
      To z twym domkiem będzie krucho!
      Ale świnka wciąż nie chciała go wpuścić do środka. Wielki zły wilk sapał i dmuchał tak tak długo, aż mały domek ze słomy rozsypał się. Pierwsza mała świnka musiała uciekać tak szybko, jak tylko potrafiła, bo inaczej wilk naprawdę by ją zjadł!

      Wkrótce potem druga mała świnka postanowiła poszukać szczęścia w szerokim świecie. Powiedziała mamie „do widzenia” i poszła sobie.
      Szybko dotarła do wysypanej żwirem drogi.
      - Jaka przyjemna droga. Mam nadzieję, że prowadzi w jakieś ciekawe miejsce, gdzie znajdę swoje szczęście – pomyślała.
      Skręciła więc w żwirową drogę.
      Wkrótce druga mała świnka spotkała człowieka niosącego wielką walizkę patyków.
      - Dzień dobry panu – przywitała się uprzejmie druga mała świnka. - Czy nie sprzedałby mi pan tej wiązki patyków. Chciała bym zbudować z nich swój domek.
      - Oczywiście – odpowiedział człowiek.
      Druga mała świnka dała mu wszystkie pieniądze za patyki.
      Wzięła wiązkę i zabrała się do pracy. Dokładnie opiłowała patyki. Potem poprzybijała je do siebie. Wkrótce zrobiła z patyków przytulny, mały domek.
      Kiedy tylko druga mała świnka wstawiła frontowe drzwi, nadszedł wielki zły wilk. Zapukał do drzwi i zawołał:
      Mała świnko, uchyl drzwi
      Pozwól wejść do środka mi!
      Kiedy druga mała świnka wyjrzała przez okno i zobaczyła wielkiego złego wilka, odpowiedziała:
      Nie otworzę drzwi przed tobą,
      Boś jest bardzo złą osobą!
      To rozwścieczyło wilka. Bardzo głośno zaryczał:
      Jak się nadmę i jak dmuchnę
      To z twym domkiem będzie krucho!
    </div>
  </article>

{% endblock %}

core/templates/core/products.html
{% extends "core/base.html" %}
{% load static %}

{% block content %}
{% if list %}
  <table class="table">
    <thead>
      <tr>
        <th scope="col">Nazwa</th>
        <th scope="col">Obrazek</th>
        <th scope="col">Cena</th>
        <th scope="col">Ilość</th>
        <th scope="col">Zakup</th>
      </tr>
    </thead>
    <tbody>
    {% for item in list %}
    <tr>
      <td class="align-middle">{{ item.name }}</td>
      <td class="align-middle">
        {% if item.image %}
        <img src="{% get_static_prefix %}core/media/{{item.image}}" height="100" width="100"/>
        {% else %}
          <img src="{% get_static_prefix %}core/media/photo5.jpg" width="100">
        {% endif %}
      </td>
      <td class="align-middle">{{ item.price }}</td>
      <td class="align-middle">{{ item.amount }}</td>
      <td class="align-middle"><button type="button" class="btn btn-danger">Kupuję</button></td>
    </tr>
    {% endfor %}
    </tbody>
  </table>
{% else %}
  <h4>Brak produktów</h4>
{% endif %}
{% endblock %}